Numpy is apython Library for creating vectors and 2D Matrices 

In [1]:
import numpy as np

In [2]:
#creating Numpy arrays by passing list 


my_list=[1,2,3,4,5,6,7,8,9]

my_arr=np.array(my_list)

my_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
my_list_2d=[[1,2,3],[4,5,6]]

my_2d_arr=np.array(my_list)

my_2d_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Here we have created a 2d Matrix

my_mat=[[1,2,3],[4,5,6],[7,8,9]]

arr=np.array(my_mat)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# np.arange() and use of reshape() in Numpy to create a 2d Matrix:

In [9]:
#arange() method in numpy creates number in between range as passed in argument
my_arr=np.arange(1,21)
my_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [10]:
#Here third argument is for step size 
my_arr=np.arange(1,21,2)
my_arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [12]:
my_mat=np.arange(1,26).reshape(5,5)
my_mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# np.zeros() method to generate arrays and matrix containing zeros

In [13]:
arr=np.zeros(25)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
arr=np.zeros(25).reshape(5,5) #first argument for rows and second argument for columns
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# np.ones( ) to genrate array containing ones:

In [17]:
arr=np.ones(24)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [18]:
arr=np.ones(24).reshape(3,8)
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

# Generating Identity matrix using np.eye() in Numpy:

In [20]:
#Here just one argument is passed which will be number of rows and also the same number of columns
arr=np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Generating evenly spaced numbers in between range using np.linspace():

In [22]:
#Here it will genrate an 10 array elements between 1 and 20 that are evenly spaced
arr=np.linspace(1,20,30)
arr

array([ 1.        ,  1.65517241,  2.31034483,  2.96551724,  3.62068966,
        4.27586207,  4.93103448,  5.5862069 ,  6.24137931,  6.89655172,
        7.55172414,  8.20689655,  8.86206897,  9.51724138, 10.17241379,
       10.82758621, 11.48275862, 12.13793103, 12.79310345, 13.44827586,
       14.10344828, 14.75862069, 15.4137931 , 16.06896552, 16.72413793,
       17.37931034, 18.03448276, 18.68965517, 19.34482759, 20.        ])

# To generate Random Numbers in array:

In [23]:
#It will generate 5 random numbers between 0 and 1
arr=np.random.rand(5)
arr

array([0.02553532, 0.57300521, 0.95320044, 0.8531125 , 0.80281564])

In [24]:
#It will generate matrix of dimension 3 x 3 containing random numbers between 0 and 1
arr=np.random.rand(3,3)
arr

array([[0.76842337, 0.63553133, 0.83805203],
       [0.79619869, 0.39069256, 0.34525449],
       [0.11799317, 0.6296607 , 0.05154435]])

In [28]:
#It will generate random 20 Numbers between 1 and 200 
arr=np.random.randint(1,200,20)
arr

array([150, 150, 103,  17, 103, 133, 101,  49,  66, 172,  29,  15, 118,
       186, 174, 128, 131, 168, 131, 177])

# Indexing of Numpy arrays:

In [29]:
myarr=np.arange(1,20)
myarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [31]:
myarr=np.arange(1,20)
print(myarr[0:4])

[1 2 3 4]


In [33]:
myarr=np.arange(1,20)
print(myarr[2:5])

[3 4 5]


# Grabbing elements from a 2d Matrix:

In [34]:
my_mat=np.arange(1,41).reshape(5,8)
my_mat

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40]])

In [36]:
#Let us grab 11,12,13
print(my_mat[1][2:5])

[11 12 13]


In [44]:
#Let us grab 21,22
#            29,30
my_mat=np.arange(1,41).reshape(5,8)
print(my_mat[2:4,4:6])

[[21 22]
 [29 30]]


# Conditional selection in Numpy array/matrix:

In [42]:
my_mat=np.arange(1,101).reshape(4,25)
my_mat

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [43]:
#Here we need to fetch only those elements that are even 
my_new_mat=my_mat[my_mat%2==0]
my_new_mat

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

# Numpy operations:

There are basically three types of Numpy operation like:
1)Array with Array
2)Array with scalers
3)Universal Array Function

In [46]:
#Here we are going to do Array with Array Operation 
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr3=arr1+arr2
arr3

array([ 6,  8, 10, 12])

In [47]:
#Here we are going to do array with sacler operation
arr3=arr1*2
arr3

array([2, 4, 6, 8])

In [56]:
#Here we are goin to use some Universal Array Function
np.min(arr1)

1

In [55]:
np.mean(arr1)

2.5

In [54]:
np.max(arr1)

4

In [53]:
np.sqrt(arr1)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [57]:
np.sum(arr1)

10